"use strict";
var boletim;
boletim = ["Maria", 10, 75];
console.log(boletim);
var estoque;
estoque = ["Feijão", 150];
console.log(estoque);
var participantes = [];
participantes.push(["José", 26]);
participantes.push(["Maria", 18]);
participantes.push(["Pedro", 16]);
console.log(participantes);
